### ISSUE TITLE
Cannot contact author

### ISSUE THREAD

**Issue by massivepenguin** [mredig/SGG_SKSpineImport#1]
Sorry for the pseudo-issue, but I've made some modifications to the project in my forked copy, and wondered if you'd be able to check them over to see if there's a more efficient way of doing things (specifically reverting a partially-changed skin). 

If you think the methods would be a useful addition to the core I'm more than happy for you to pull them in :)

**Comment by mredig** [comment]
Wow! I haven't had time to dig into this yet, but it looks really cool! If you want to go ahead and make a pull request, I'll likely accept it after I actually have a chance to look it over.

Also, I agree that they should make messaging a bit easier on here... (than again, I'm very new to contributing on the site, so maybe I overlooked something)

**Comment by massivepenguin** [comment]
I'll create a pull request tomorrow once I've restored your readme (don't want to overwrite your work!). If you add an email address or website to your profile, people will be able to contact you... in the meantime I think you can call this issue closed ;)

**Comment by mredig** [comment]
That almost seems logical!
