### ISSUE TITLE
queued animation bug

### ISSUE THREAD

**Issue by nikki2pro** [mredig/SGG_SKSpineImport#11]
First, thank you so much that you let us use this library!

Whenever I used queue animation stuff, I got the runtime error.
(Swift 2.1 & Xcode 7.1 & iOS9)

I checked  the "SGG_Spine.h" file and found the propery as below.

```
@property (nonatomic, assign) NSString* queuedAnimation;
```

I thought this property should be "retain" rather than "assign", because NSString\* means pointer.
So I changed it like below and the queue animation stuff worked fine.

```
@property (nonatomic, retain) NSString* queuedAnimation;
```

Please check.

**Comment by mredig** [comment]
Gonna be honest - I don't know what assign does. It became a habit to type
it after I followed some tutorials, but I vaguely recall looking up what it
does and deciding that it was pointless (I don't use it anymore).

Anyway, feel free to make a pull request.
