### ISSUE TITLE
Do you support latest spine format? 

### ISSUE THREAD

**Issue by zyunlongz** [mredig/SGG_SKSpineImport#17]
@mredig   Hi, I appreciate your great work, this library is very simple and easy use compare to other third party spine libs. But I can't get my latest spine format file work, with a single atlas file and a big png rather than an atlas folder. If this lib support, how can I get the spine format work?

**Comment by titman** [comment]
Same confusion.

**Comment by mredig** [comment]
Sorry about the slow response. I haven't updated or even looked at the latest developments in Spine in a while. If there are any format changes, I have not made any adjustments to compensate for them. Sorry. :(

**Comment by riyanpratamap** [comment]
> @mredig Hi, I appreciate your great work, this library is very simple and easy use compare to other third party spine libs. But I can't get my latest spine format file work, with a single atlas file and a big png rather than an atlas folder. If this lib support, how can I get the spine format work?

hi, do you find any solution?
