### ISSUE TITLE
How can i use  mesh？

### ISSUE THREAD

**Issue by al1020119** [mredig/SGG_SKSpineImport#20]

**Comment by mredig** [comment]
There isn't support for FFD (I assume that's what you mean by mesh) in this runtime.

**Comment by al1020119** [comment]
First of all, thank you for providing such a good library support. Our sketch is done by Spine. We need to support the grid function. After using your library, we found that the grid function can not be used. Can you support the grid?

**Comment by mredig** [comment]
I don't have the expertise to implement that, sorry. If you are able to modify the code to support a solution, though, please create a pull request!
