### ISSUE TITLE
Animations are not running in swift

### ISSUE THREAD

**Issue by nikki2pro** [mredig/SGG_SKSpineImport#9]
When I try to add a sprite animation in iOS9 and swift, the sprite is showing but it's not animating.

I did the bridging header stuff, added the SpineImport files, added the json and atlas files, and put some code like below.

<img width="963" alt="2015-10-21 8 12 28" src="https://cloud.githubusercontent.com/assets/15229995/10634968/415cf23a-7830-11e5-8b0b-4b39b608be89.png">

<img width="382" alt="2015-10-21 8 19 04" src="https://cloud.githubusercontent.com/assets/15229995/10635076/1202169a-7831-11e5-9c16-de9f16d9d18c.png">

When I tried few weeks ago, it worked fine, but it's not working now.

Please help, Thanks!!

**Comment by mredig** [comment]
I haven't tried anything in swift yet, but did you call the animation
activation in the update method?

**Comment by nikki2pro** [comment]
Hello, Thank you for your comment!

I called the animation in "didMoveToView", so it's one time thing. But I believe it's a repeating animation because I put -1 for andCount: like below.

```
hero.runAnimation("run", andCount: -1)
```

-1 means repeating forever, right? 

Anyway, I also tried it in the update method, it didn't work.

**Comment by nikki2pro** [comment]
oops! I didn't activated the animation(hero.activateAnimations())... Now I get it. Thank you very much!!!!!!!
